package fr.elliot.qonos.Enum;

public enum Competences
{
    ENDURANCE_MENTAL, ENDURANCE_PHYSIQUE, INITIATIVE, DISCRETION_URBAINE, DISCRETION_RURALE, CHARISME, PLANIFICATION, MEMOIRE, VUE, OUIE, TOUCHER, GOUT, ODORAT,
    CORPS_A_CORPS_BRUTE, CORPS_A_CORPS_BASE, TIR_BRUTE, TIR_BASE, PARADE, SEDUCTION;
}
