package fr.elliot.qonos.Enum;

public enum Grade
{
    SOLDAT_IMPERIAL, OFFICIER_IMPERIAL, SERGENT_IMPERIAL, LIEUTENANT_IMPERIAL, COMMANDANT_IMPERIAL, GENERAL_IMPERIAL, OFFICIER_STRATEGE, SERGENT_STRATEGE,
    LIEUTENANT_STARTEGE, GRAND_STRATEGE, PREMIER_STARTEGE, GARDE_IMPERIAL, GARDE_INFORMATEUR, GARDE_ESPION, GARDE_PRINCIPAL, COMMANDANT_GARDE, GARDE_SUPERIEUR,
    MEDECIN, MEDECIN_DE_L_ORDRE, MEECIN_SECONDAIRE, MEDECIN_PRINCIPAL, GRAND_MEDECIN, MEDECIN_CHEF, ARTISTE, ARTISTE_CONNU, GRAND_ARTISTE, ARTISTE_OFFICIEL,
    ARTISTE_IMPERIAL, ARTISTE_LIBRE, SCIENTIFIQUE_IMPERIAL, THEORICIEN, CHERCHEUR, EXPERIMENTATEUR_IMPERIAL, SCIENTIFIQUE_CHEF, SCIENTIFIQUE_DE_L_EMPEREUR;
}
